name: Create GitHub Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true